"""add session_price to therapist_profile

Revision ID: 1595ead6aff2
Revises: 678952a56173
Create Date: 2026-03-09 08:06:31.945737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1595ead6aff2'
down_revision: Union[str, Sequence[str], None] = '678952a56173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapist_profiles', sa.Column('session_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapist_profiles', 'session_price')
    # ### end Alembic commands ###
