"""add reschedule relationship

Revision ID: 681825de8c60
Revises: 728da1d1c3aa
Create Date: 2026-03-08 20:58:58.032665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681825de8c60'
down_revision: Union[str, Sequence[str], None] = '728da1d1c3aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_rescheduled_from_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'appointments', ['rescheduled_from_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_rescheduled_from_id_fkey'), 'appointments', 'appointments', ['rescheduled_from_id'], ['id'])
    # ### end Alembic commands ###
