"""make therapist_profile_id not null

Revision ID: 7b5e1a2e7245
Revises: 827d9a6f4010
Create Date: 2026-03-12 15:34:01.466134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5e1a2e7245'
down_revision: Union[str, Sequence[str], None] = '827d9a6f4010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('therapist_availabilities', 'therapist_profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('therapist_availabilities', 'therapist_profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
