"""add therapist_profile_id to therapist_availabilities

Revision ID: 827d9a6f4010
Revises: 1595ead6aff2
Create Date: 2026-03-12 10:26:35.197459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827d9a6f4010'
down_revision: Union[str, Sequence[str], None] = '1595ead6aff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapist_availabilities', sa.Column('therapist_profile_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('therapist_availabilities_therapist_user_id_fkey'), 'therapist_availabilities', type_='foreignkey')
    op.create_foreign_key(None, 'therapist_availabilities', 'therapist_profiles', ['therapist_profile_id'], ['id'])
    op.drop_column('therapist_availabilities', 'therapist_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapist_availabilities', sa.Column('therapist_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'therapist_availabilities', type_='foreignkey')
    op.create_foreign_key(op.f('therapist_availabilities_therapist_user_id_fkey'), 'therapist_availabilities', 'users', ['therapist_user_id'], ['id'])
    op.drop_column('therapist_availabilities', 'therapist_profile_id')
    # ### end Alembic commands ###
