"""add foto_url and other fields to therapist_profile

Revision ID: 98af45db5ce1
Revises: 40dafdbd8482
Create Date: 2026-03-15 14:57:22.823589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98af45db5ce1'
down_revision: Union[str, Sequence[str], None] = '40dafdbd8482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 🔥 CORREÇÃO: Remover tabelas com CASCADE na ordem correta
    op.execute('DROP TABLE IF EXISTS availability_slots CASCADE')
    op.execute('DROP TABLE IF EXISTS availability_periods CASCADE')
    op.execute('DROP TABLE IF EXISTS appointment_events CASCADE')
    
    # Adicionar novas colunas
    op.add_column('therapist_profiles', sa.Column('foto_url', sa.String(length=500), nullable=True, comment='URL da foto de perfil do terapeuta'))
    op.add_column('therapist_profiles', sa.Column('experiencia', sa.Text(), nullable=True, comment='Descrição da experiência profissional'))
    op.add_column('therapist_profiles', sa.Column('abordagem', sa.String(length=500), nullable=True, comment='Abordagem terapêutica (separada por vírgulas)'))
    op.add_column('therapist_profiles', sa.Column('idiomas', sa.String(length=200), nullable=True, comment='Idiomas falados (separados por vírgulas)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapist_profiles', 'idiomas')
    op.drop_column('therapist_profiles', 'abordagem')
    op.drop_column('therapist_profiles', 'experiencia')
    op.drop_column('therapist_profiles', 'foto_url')
    
    # 🔥 CORREÇÃO: Recriar tabelas no downgrade
    op.create_table('availability_periods',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('therapist_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
        sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['therapist_profile_id'], ['therapist_profiles.id'], name=op.f('availability_periods_therapist_profile_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('availability_periods_pkey'))
    )
    
    op.create_table('availability_slots',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('period_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('weekday', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
        sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['period_id'], ['availability_periods.id'], name=op.f('availability_slots_period_id_fkey'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('availability_slots_pkey'))
    )
    
    op.create_table('appointment_events',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('actor_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('old_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column('new_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('appointment_events_actor_user_id_fkey')),
        sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('appointment_events_appointment_id_fkey'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('appointment_events_pkey'))
    )
    
    op.create_index(op.f('idx_appointment_events_appointment_id'), 'appointment_events', ['appointment_id'], unique=False)
    op.create_index(op.f('idx_appointment_events_actor_user_id'), 'appointment_events', ['actor_user_id'], unique=False)
    # ### end Alembic commands ###