"""add_appointment_status_enum

Revision ID: 6a3a15206fc1
Revises: 819586b99488
Create Date: 2026-03-04 22:57:21.448562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3a15206fc1'
down_revision: Union[str, Sequence[str], None] = '819586b99488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('rescheduled_from_id', sa.Integer(), nullable=True))
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('scheduled', 'confirmed', 'cancelled_by_patient', 'cancelled_by_therapist', 'cancelled_by_admin', 'proposed', 'completed', 'no_show', 'rescheduled', name='appointment_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.create_index('ix_appointments_patient_starts_at', 'appointments', ['patient_user_id', 'starts_at'], unique=False)
    op.create_index('ix_appointments_therapist_starts_at', 'appointments', ['therapist_user_id', 'starts_at'], unique=False)
    op.create_foreign_key(None, 'appointments', 'appointments', ['rescheduled_from_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index('ix_appointments_therapist_starts_at', table_name='appointments')
    op.drop_index('ix_appointments_patient_starts_at', table_name='appointments')
    op.alter_column('appointments', 'status',
               existing_type=sa.Enum('scheduled', 'confirmed', 'cancelled_by_patient', 'cancelled_by_therapist', 'cancelled_by_admin', 'proposed', 'completed', 'no_show', 'rescheduled', name='appointment_status_enum'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.drop_column('appointments', 'rescheduled_from_id')
    # ### end Alembic commands ###
